version: '2'
name: vecfleet_vehicles
services:
  # db 
  vecfleet-vehicles-mariadb:
    container_name: vecfleet_vehicles_mysql
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=vecfleet
      - MARIADB_DATABASE=vecfleet
    volumes:
      - './data:/bitnami/mariadb/data'
    ports:
      - '8901:3306'
  # API 
  vecfleet_vehicles-api:
    container_name: vecfleet_vehicles_api
    image: docker.io/bitnami/laravel:9
    ports:
      - '8902:8000'
    environment:
      - DB_HOST=vecfleet-vehicles-mariadb
      - DB_PORT=3306
      - DB_USERNAME=vecfleet
      - DB_DATABASE=vecfleet
    volumes:
      - './api/v1:/app'
    depends_on:
      - vecfleet-vehicles-mariadb
  # phpmyadmin
  vecfleet_vehicles-phpmyadmin:
    container_name: vecfleet_vehicles_phpmyadmin
    restart: always
    image: phpmyadmin
    ports:
      - 8903:80
    environment:
      PMA_HOSTS: vecfleet-vehicles-mariadb
  # Web APP 
  vecfleet-vehicles-frontend:
    container_name: vecfleet_vehicles_frontend
    build: .
    volumes:
      - './refine-frontend:/app'
    # environment:
    #   # is recommended only for development.
    #   # - ALLOW_EMPTY_PASSWORD
    #   - ALLOW_EMPTY_PASSWORD=yes
    #   - MARIADB_USER=vecfleet
    #   - MARIADB_DATABASE=vecfleet
    ports:
      - '8900:3000'
    depends_on:
      - vecfleet_vehicles-api
